### ISSUE TITLE
BasicXrApp::RenderFrame nearly always fails

### ISSUE THREAD

**Issue by tksharpless** [microsoft/OpenXR-MixedReality#69]
Platform is Dell 5577 gaming laptop + IIG 630 + nVidia GTX1050 + Win10 1903.  Latest video driver installed. 
 Building from this repo with VS 2019 + vcpkg.

The app has run successfully once, after a reboot.  Every other time it has immediately failed with debug message

> Unhandled Exception: XrResult failure [XR_ERROR_RUNTIME_FAILURE]
    Origin: xrEndFrame(m_session.Get(), &frameEndInfo)
    Source: D:\Packages\OpenXR-MixedReality\samples\BasicXrApp\OpenXrProgram.cpp:662

On this same system, Microsoft Edge always fails to enter VR -- it shows the 'launching VR' splash then reverts to flat display (but believes it is still in VR mode).  The 'OpenXR Developer Tools' app fails to show anything, but also gives no error indication and seems to think it is working .   

SteamVR apps run normally, so  I suspect some incompatibility in the WMR OpenXR runtime.  

I hope you can help me resolve this

**Comment by yl-msft** [comment]
@tksharpless  the team is looking at your report and suspecting a few situations that might leads to this problem.   A few clues might help us diagnose this.
1. Can you tell us runtime version you are using?  It's easy to check using ["OpenXR Developer Tools" app](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr-getting-started#getting-the-openxr-developer-tools-for-windows-mixed-reality)
1. When you run the app in Visual Studio debug, what else do you see in the output window?  Is there any exceptions or openxr error messages before the line you posted?
1. Can you send us a DXDiag.txt?  we suspect if this is related to the hybrid gpu layout on your laptop.

**Comment by tksharpless** [comment]
Thanks, yl-msft.
Runtime version 103.2010.8005
No other debug messages that I can recall.  Will run it again tomorrow and let you know.
There is no file called DXDiag.txt on my system. What is that and how do I make one?
I am also pretty sure this has to do with the IIG + gpu configuration, which causes trouble for various s/w.

**Comment by tksharpless** [comment]
[DxDiag.txt](https://github.com/microsoft/OpenXR-MixedReality/files/5468565/DxDiag.txt)
Here is the full debug output ---
'BasicXrApp_win32.exe' (Win32): Loaded 'D:\Packages\OpenXR-MixedReality\bin\Debug\x64\BasicXrApp_win32.exe'. Symbols loaded.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ntdll.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\kernel32.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\KernelBase.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\apphelp.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\combase.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ucrtbase.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\dxgi.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\d3d11.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\D3DCompiler_47.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\rpcrt4.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msvcrt.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msvcrt.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\msvcrt.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\cryptsp.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\win32u.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\bcryptprimitives.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\kernel.appcore.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\gdi32.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\gdi32full.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'D:\Packages\OpenXR-MixedReality\bin\Debug\x64\openxr_loader.dll'. Symbols loaded.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msvcp_win.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msvcp140d.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\user32.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\advapi32.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\vcruntime140_1d.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\sechost.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\vcruntime140d.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\vcruntime140d.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\vcruntime140d.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ucrtbased.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DXCore.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ucrtbased.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\ucrtbased.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ucrtbased.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ucrtbased.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\ucrtbased.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\ucrtbased.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\cfgmgr32.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\imm32.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\MixedRealityRuntime.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\oleaut32.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.StateRepositoryCore.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\Program Files\WindowsApps\Microsoft.WindowsMixedReality.Runtime_103.2010.8005.0_x64__8wekyb3d8bbwe\x64\WinXrRuntime.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\version.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\D3D12.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\d2d1.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DWrite.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\clbcatq.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\AppContracts.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\SHCore.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\WinTypes.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.StateRepositoryPS.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\AppXDeploymentClient.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\FirewallAPI.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\StateRepository.Core.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\dnsapi.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ws2_32.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\nsi.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\IPHLPAPI.DLL'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\fwbase.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.Shell.ServiceHostBuilder.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\OneCoreUAPCommonProxyStub.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\OnDemandBrokerClient.dll'. 
onecoreuap\base\appmodel\appcontracts\lib\odbexecutor.cpp(115)\AppContracts.dll!00007FFA3BE1681B: (caller: 00007FFA3BDC4A35) ReturnHr(1) tid(59f4) 80073D54 The process has no package identity.
    CallContext:[\AppServiceBackgroundTask] 
The thread 0xd20 has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\twinapi.appcore.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\rmclient.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.Perception.Stub.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.Mirage.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ntmarta.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\dcomp.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\CoreMessaging.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\rometadata.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\WinMetadata\Windows.Perception.winmd'. Module was built without symbols.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\WinMetadata\Windows.UI.winmd'. Module was built without symbols.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ResourcePolicyClient.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\ResourcePolicyClient.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\windows.storage.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\profapi.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\powrprof.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\umpdc.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\shlwapi.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvdlistx.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvdlistx.dll'
Using graphics adapter NVIDIA GeForce GTX 1050
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DXGIDebug.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvldumdx.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msasn1.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\cryptnet.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\crypt32.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\cryptbase.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\wintrust.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\imagehlp.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\rsaenh.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\bcrypt.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvwgf2umx.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\winmm.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\winmmbase.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\winmmbase.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\winmmbase.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\winmmbase.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\winmmbase.dll'
The thread 0x3c7c has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\shell32.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\shell32.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\shell32.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\nvspcap64.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ole32.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\d3d11_3SDKLayers.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\uxtheme.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msctf.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\dxilconv.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\D3DSCache.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\userenv.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\dxilconv.dll'
The thread 0xb80 has exited with code 0 (0x0).
The thread 0x2d94 has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\InputHost.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\CoreUIComponents.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\propsys.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\dxilconv.dll'. 
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\dxilconv.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\Program Files\WindowsApps\Microsoft.WindowsMixedReality.Runtime_103.2010.8005.0_x64__8wekyb3d8bbwe\x64\WinXrHolographicInputExtensions.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\PerceptionDevice.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.UI.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\TextInputFramework.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.Gaming.Input.dll'. 
Exception thrown at 0x00007FFA6C473B29 (KernelBase.dll) in BasicXrApp_win32.exe: WinRT originate error - 0x80070057 : 'The provided value was outside of the range of valid values.'.
analog\input\mirage\publicapi\compositionlayerd3d12bufferprovider.cpp(201)\Windows.Mirage.dll!00007FF9DAD31E9A: (caller: 00007FF9DACBFA25) ReturnHr(1) tid(5a74) 80070057 The parameter is incorrect.
    Msg:[deviceAdapterLuid.LowPart == m_outputAdapterLuid.LowPart && deviceAdapterLuid.HighPart == m_outputAdapterLuid.HighPart] 
analog\input\mirage\publicapi\holographiccamera.cpp(531)\Windows.Mirage.dll!00007FF9DACBFA43: (caller: 00007FF9DACBF811) ReturnHr(2) tid(5a74) 80070057 The parameter is incorrect.
Exception thrown at 0x00007FFA6C473B29 in BasicXrApp_win32.exe: Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x000000C4FF2FCF80.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\iertutil.dll'. 
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\WinMetadata\Windows.Graphics.winmd'. Module was built without symbols.
Exception thrown at 0x00007FFA6C473B29 (KernelBase.dll) in BasicXrApp_win32.exe: WinRT originate error - 0x80070057 : 'The provided value was outside of the range of valid values.'.
analog\input\mirage\publicapi\compositionlayerd3d12bufferprovider.cpp(201)\Windows.Mirage.dll!00007FF9DAD31E9A: (caller: 00007FF9DACBFA25) ReturnHr(3) tid(5a74) 80070057 The parameter is incorrect.
    Msg:[deviceAdapterLuid.LowPart == m_outputAdapterLuid.LowPart && deviceAdapterLuid.HighPart == m_outputAdapterLuid.HighPart] 
analog\input\mirage\publicapi\holographiccamera.cpp(531)\Windows.Mirage.dll!00007FF9DACBFA43: (caller: 00007FF9DACBF811) ReturnHr(4) tid(5a74) 80070057 The parameter is incorrect.
Exception thrown at 0x00007FFA6C473B29 in BasicXrApp_win32.exe: Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x000000C4FF2FCE70.
Exception thrown at 0x00007FFA6C473B29 in BasicXrApp_win32.exe: Microsoft C++ exception: std::logic_error at memory location 0x000000C4FF2FEA08.
The thread 0x2e60 has exited with code 0 (0x0).
Exception thrown at 0x00007FFA6C473B29 (KernelBase.dll) in BasicXrApp_win32.exe: WinRT originate error - 0x80070057 : 'The provided value was outside of the range of valid values.'.
Exception thrown at 0x00007FFA6C473B29 in BasicXrApp_win32.exe: Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x000000C4FF2F9F00.
analog\input\mirage\publicapi\compositionlayerd3d12bufferprovider.cpp(201)\Windows.Mirage.dll!00007FF9DAD31E9A: (caller: 00007FF9DACBFA25) ReturnHr(5) tid(5a74) 80070057 The parameter is incorrect.
    Msg:[deviceAdapterLuid.LowPart == m_outputAdapterLuid.LowPart && deviceAdapterLuid.HighPart == m_outputAdapterLuid.HighPart] 
analog\input\mirage\publicapi\holographiccamera.cpp(531)\Windows.Mirage.dll!00007FF9DACBFA43: (caller: 00007FF9DACBF811) ReturnHr(6) tid(5a74) 80070057 The parameter is incorrect.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\PerceptionDevice.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\Program Files\WindowsApps\Microsoft.WindowsMixedReality.Runtime_103.2010.8005.0_x64__8wekyb3d8bbwe\x64\WinXrHolographicInputExtensions.dll'
The thread 0x58e4 has exited with code 0 (0x0).
The thread 0x5124 has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\MixedRealityRuntime.dll'
The thread 0x1134 has exited with code 0 (0x0).
The thread 0x2454 has exited with code 0 (0x0).
The thread 0x5bd8 has exited with code 0 (0x0).
The thread 0x5550 has exited with code 0 (0x0).
The thread 0x4df4 has exited with code 0 (0x0).
The thread 0x529c has exited with code 0 (0x0).
The thread 0x590c has exited with code 0 (0x0).
The thread 0x4850 has exited with code 0 (0x0).
The thread 0x3774 has exited with code 0 (0x0).
The thread 0x2c44 has exited with code 0 (0x0).
The thread 0x2404 has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\winmmbase.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\winmm.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvwgf2umx.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvldumdx.dll'
Unhandled Exception: XrResult failure [XR_ERROR_RUNTIME_FAILURE]
    Origin: xrEndFrame(m_session.Get(), &frameEndInfo)
    Source: D:\Packages\OpenXR-MixedReality\samples\BasicXrApp\OpenXrProgram.cpp:662

**Comment by tksharpless** [comment]
From this debug output I get the impression that the runtime is trying to use an invalid output device logical unit ID.  Not surprising, given that Intel Integrated Graphics controls the video output port.  Previously I sent the DXDiag listing obtained with the VR headset connected; it is quite different with an external monitor on the HDMI port, or nothing there.  I attach all 3 listings.
[DxDiag-ExtMonitor.txt](https://github.com/microsoft/OpenXR-MixedReality/files/5485781/DxDiag-ExtMonitor.txt)
[DxDiag-OpenHDMIport.txt](https://github.com/microsoft/OpenXR-MixedReality/files/5485782/DxDiag-OpenHDMIport.txt)
[DxDiag-VRhmd.txt](https://github.com/microsoft/OpenXR-MixedReality/files/5485783/DxDiag-VRhmd.txt)

**Comment by yl-msft** [comment]
@tksharpless ,  this does look like related to the hybrid GPU issue.  We had a workaround in our preview runtime to mitigate an issue like this.  I wonder if we can try it out our preview runtime?

1. install "openxr developer tools" app
https://www.microsoft.com/en-us/p/openxr-developer-tools-for-windows-mixed-reality/9n5cvvl23qbt

2. turn on preview runtime, then restart your app.

![image](https://user-images.githubusercontent.com/33265158/98159216-07824080-1e91-11eb-80d0-680c0c27c6d3.png)

**Comment by tksharpless** [comment]
Hi. I have enabled preview runtime; OpenXR Developer Tools reports runtime version 104.2010.27002.
It still fails to display its demo scene, without error message. And the sample app still gets an exception from the runtime.  Debug log follows
'BasicXrApp_win32.exe' (Win32): Loaded 'D:\Packages\OpenXR-MixedReality\bin\Debug\x64\BasicXrApp_win32.exe'. Symbols loaded.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ntdll.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\kernel32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\KernelBase.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\combase.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\d3d11.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\dxgi.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\D3DCompiler_47.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msvcrt.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\rpcrt4.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msvcrt.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\msvcrt.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\cryptsp.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\win32u.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\win32u.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'D:\Packages\OpenXR-MixedReality\bin\Debug\x64\openxr_loader.dll'. Symbols loaded.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\win32u.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msvcp140d.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\gdi32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\vcruntime140d.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\gdi32full.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msvcp_win.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\user32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\advapi32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\vcruntime140_1d.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ucrtbased.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\ucrtbased.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ucrtbased.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\ucrtbased.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\sechost.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ucrtbased.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DXCore.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\cfgmgr32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\imm32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\MixedRealityRuntime.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\oleaut32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.StateRepositoryCore.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\Program Files\WindowsApps\Microsoft.WindowsMixedReality.Runtime_103.2010.8005.0_x64__8wekyb3d8bbwe\x64\WinXrRuntime.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\d2d1.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DWrite.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\version.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\D3D12.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\clbcatq.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\AppContracts.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\SHCore.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\WinTypes.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.StateRepositoryPS.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\AppXDeploymentClient.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\FirewallAPI.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\StateRepository.Core.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\dnsapi.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ws2_32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\nsi.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\IPHLPAPI.DLL'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\fwbase.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.Shell.ServiceHostBuilder.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\OneCoreUAPCommonProxyStub.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\OnDemandBrokerClient.dll'. Cannot find or open the PDB file.
onecoreuap\base\appmodel\appcontracts\lib\odbexecutor.cpp(115)\AppContracts.dll!00007FFA3BE1681B: (caller: 00007FFA3BDC4A35) ReturnHr(1) tid(5434) 80073D54 The process has no package identity.
    CallContext:[\AppServiceBackgroundTask] 
The thread 0x8ccc has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\twinapi.appcore.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\rmclient.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.Perception.Stub.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.Mirage.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ntmarta.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\CoreMessaging.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\dcomp.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\rometadata.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\WinMetadata\Windows.Perception.winmd'. Module was built without symbols.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\WinMetadata\Windows.UI.winmd'. Module was built without symbols.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\Program Files\WindowsApps\Microsoft.WindowsMixedReality.PreviewRuntime_104.2010.27002.0_x64__8wekyb3d8bbwe\x64\WinXrRuntime.dll'. Cannot find or open the PDB file.
onecoreuap\base\appmodel\appcontracts\lib\odbexecutor.cpp(115)\AppContracts.dll!00007FFA3BE1681B: (caller: 00007FFA3BDC4A35) ReturnHr(2) tid(5434) 80073D54 The process has no package identity.
    CallContext:[\AppServiceBackgroundTask] 
The thread 0x9b1c has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\threadpoolwinrt.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ResourcePolicyClient.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\ResourcePolicyClient.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\windows.storage.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\profapi.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\powrprof.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\umpdc.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\shlwapi.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvdlistx.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvdlistx.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvdlistx.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvdlistx.dll'
Using graphics adapter NVIDIA GeForce GTX 1050
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DXGIDebug.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvldumdx.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msasn1.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\cryptnet.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\crypt32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\cryptbase.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\wintrust.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\imagehlp.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\rsaenh.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\bcrypt.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvwgf2umx.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\winmm.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\winmmbase.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\winmmbase.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\winmmbase.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\winmmbase.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\winmmbase.dll'
The thread 0x9b60 has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\shell32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\shell32.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\shell32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\nvspcap64.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\ole32.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\d3d11_3SDKLayers.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\uxtheme.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\msctf.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\dxilconv.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\D3DSCache.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\userenv.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\dxilconv.dll'
The thread 0x8fd4 has exited with code 0 (0x0).
The thread 0x8fd8 has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\InputHost.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\CoreUIComponents.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\propsys.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\NvCamera\NvCameraAllowlisting64.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\dxilconv.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\dxilconv.dll'
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\Program Files\WindowsApps\Microsoft.WindowsMixedReality.PreviewRuntime_104.2010.27002.0_x64__8wekyb3d8bbwe\x64\WinXrHolographicInputExtensions.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\PerceptionDevice.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.UI.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\TextInputFramework.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\Windows.Gaming.Input.dll'. Cannot find or open the PDB file.
Exception thrown at 0x00007FFA6C473B29 (KernelBase.dll) in BasicXrApp_win32.exe: WinRT originate error - 0x80070057 : 'The provided value was outside of the range of valid values.'.
analog\input\mirage\publicapi\compositionlayerd3d12bufferprovider.cpp(201)\Windows.Mirage.dll!00007FF9DAD31E9A: (caller: 00007FF9DACBFA25) ReturnHr(1) tid(9bf0) 80070057 The parameter is incorrect.
    Msg:[deviceAdapterLuid.LowPart == m_outputAdapterLuid.LowPart && deviceAdapterLuid.HighPart == m_outputAdapterLuid.HighPart] 
analog\input\mirage\publicapi\holographiccamera.cpp(531)\Windows.Mirage.dll!00007FF9DACBFA43: (caller: 00007FF9DACBF811) ReturnHr(2) tid(9bf0) 80070057 The parameter is incorrect.
Exception thrown at 0x00007FFA6C473B29 in BasicXrApp_win32.exe: Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x000000D3B38FCB50.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\pdh.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\iertutil.dll'. Cannot find or open the PDB file.
'BasicXrApp_win32.exe' (Win32): Loaded 'C:\WINDOWS\System32\WinMetadata\Windows.Graphics.winmd'. Module was built without symbols.
Exception thrown at 0x00007FFA6C473B29 (KernelBase.dll) in BasicXrApp_win32.exe: WinRT originate error - 0x80070057 : 'The provided value was outside of the range of valid values.'.
analog\input\mirage\publicapi\compositionlayerd3d12bufferprovider.cpp(201)\Windows.Mirage.dll!00007FF9DAD31E9A: (caller: 00007FF9DACBFA25) ReturnHr(3) tid(9bf0) 80070057 The parameter is incorrect.
    Msg:[deviceAdapterLuid.LowPart == m_outputAdapterLuid.LowPart && deviceAdapterLuid.HighPart == m_outputAdapterLuid.HighPart] 
analog\input\mirage\publicapi\holographiccamera.cpp(531)\Windows.Mirage.dll!00007FF9DACBFA43: (caller: 00007FF9DACBF811) ReturnHr(4) tid(9bf0) 80070057 The parameter is incorrect.
Exception thrown at 0x00007FFA6C473B29 in BasicXrApp_win32.exe: Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x000000D3B38FCD20.
Exception thrown at 0x00007FFA6C473B29 in BasicXrApp_win32.exe: Microsoft C++ exception: std::logic_error at memory location 0x000000D3B38FE808.
The thread 0x8ff4 has exited with code 0 (0x0).
Exception thrown at 0x00007FFA6C473B29 (KernelBase.dll) in BasicXrApp_win32.exe: WinRT originate error - 0x80070057 : 'The provided value was outside of the range of valid values.'.
analog\input\mirage\publicapi\compositionlayerd3d12bufferprovider.cpp(201)\Windows.Mirage.dll!00007FF9DAD31E9A: (caller: 00007FF9DACBFA25) ReturnHr(5) tid(9bf0) 80070057 The parameter is incorrect.
    Msg:[deviceAdapterLuid.LowPart == m_outputAdapterLuid.LowPart && deviceAdapterLuid.HighPart == m_outputAdapterLuid.HighPart] 
analog\input\mirage\publicapi\holographiccamera.cpp(531)\Windows.Mirage.dll!00007FF9DACBFA43: (caller: 00007FF9DACBF811) ReturnHr(6) tid(9bf0) 80070057 The parameter is incorrect.
Exception thrown at 0x00007FFA6C473B29 in BasicXrApp_win32.exe: Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x000000D3B38F9E90.
The thread 0x8d98 has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\PerceptionDevice.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\Program Files\WindowsApps\Microsoft.WindowsMixedReality.PreviewRuntime_104.2010.27002.0_x64__8wekyb3d8bbwe\x64\WinXrHolographicInputExtensions.dll'
The thread 0x8fc4 has exited with code 0 (0x0).
The thread 0x8fe8 has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\MixedRealityRuntime.dll'
The thread 0x9b64 has exited with code 0 (0x0).
The thread 0x9be0 has exited with code 0 (0x0).
The thread 0x9b90 has exited with code 0 (0x0).
The thread 0x9b98 has exited with code 0 (0x0).
The thread 0x9b94 has exited with code 0 (0x0).
The thread 0x9b6c has exited with code 0 (0x0).
The thread 0x9b70 has exited with code 0 (0x0).
The thread 0x9b68 has exited with code 0 (0x0).
The thread 0x9b74 has exited with code 0 (0x0).
The thread 0x5c44 has exited with code 0 (0x0).
The thread 0x9b84 has exited with code 0 (0x0).
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\winmmbase.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\winmm.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvwgf2umx.dll'
'BasicXrApp_win32.exe' (Win32): Unloaded 'C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_73ed1c151611a451\nvldumdx.dll'
Unhandled Exception: XrResult failure [XR_ERROR_RUNTIME_FAILURE]
    Origin: xrEndFrame(m_session.Get(), &frameEndInfo)
    Source: d:\packages\openxr-mixedreality\samples\basicxrapp\openxrprogram.cpp:662

The thread 0x9ad8 has exited with code 1 (0x1).
The thread 0x5434 has exited with code 1 (0x1).
The thread 0x8fb8 has exited with code 1 (0x1).
The thread 0x8fc8 has exited with code 1 (0x1).
The thread 0x9b5c has exited with code 1 (0x1).
The thread 0x9b38 has exited with code 1 (0x1).
The thread 0x9b54 has exited with code 1 (0x1).
The thread 0x6ad4 has exited with code 1 (0x1).
The thread 0x9ae0 has exited with code 1 (0x1).
The thread 0x7ca8 has exited with code 1 (0x1).
The thread 0x9a90 has exited with code 1 (0x1).
The thread 0x8f70 has exited with code 1 (0x1).
The thread 0x8ca8 has exited with code 1 (0x1).
The thread 0x9438 has exited with code 1 (0x1).
The thread 0x8ff0 has exited with code 1 (0x1).
The program '[39916] BasicXrApp_win32.exe' has exited with code 1 (0x1).

**Comment by tksharpless** [comment]
Hi, wondering if there is any progress on this issue?  
MS should consider it important since it seems to make Edge fail too, and there are plenty of IIG + nVidia gaming laptops out there.

**Comment by tksharpless** [comment]
I did this and the app (and Edge) still fail.

**Comment by yl-msft** [comment]
@tksharpless ,  we've pushed out a patch runtime that fixed a few issues related to hybrid GPU issues.  Though it's not specifically target at wrong adaptorId error but it might help.  Would like you to try this out.  Go to Store and hit Update button to ensure update.
![image](https://user-images.githubusercontent.com/33265158/100933963-eff3a300-34a2-11eb-9637-536a5171c4a7.png)

**Comment by tksharpless** [comment]
Store reports OpenXR runtime  updated  on 11/27.  However the OpenXR Tools app still reports the runtime version as 104.2010.27002.  Is there something I can do to force an update?
I have done some experiments with SteamVR OpenXR runtime.  That allows the Tools demo scene to display right, and Edge to get into VR - but only when I  switch runtimes on the fly and run the apps outside the WMR portal.   Otherwise (for example after a reboot) the Tool and Portal complain  of "unknown runtime" and Edge falls back to WebVR  mode!  This hotile behavior makes it hard to do much testing.  But the basic result is clear: Valve's runtime works on my machine, Microsoft's does not.  Please move this concern forward if you can.
I can also  report that both runtimes support SteamVR in almost all VR modes, incljding immersive WebXR in Firefox (running on dekstop with SteamVR as host).  So it looks like there is just some setup glitch between Win10 and MS OpenXR.  I look forward to a fix that will make Edge and other MS apps work as intended.

**Comment by brycehutchings** [comment]
If you are seeing version 104.* then you are using the preview runtime which we haven't updated with the hotfix yet. Try turning off the preview runtime and see if you have 103.2011.17003.0 (also, I just finished the rollout of 103.2011.17003.0 a moment ago so there is a chance you haven't gotten it yet).

**Comment by tksharpless** [comment]
Thx Bryce.  
Now have 103.2011.17003, but no dice.  DevTools demo still does not show, and Edge still crashes out of VR before displaying anything.
And there are weird curvy white lines over everything in the Portal, but not in SteamVR.

**Comment by brycehutchings** [comment]
Could you try forcing the runtime to work in D3D11 mode? Run the following from command-line:

```reg add HKCU\SOFTWARE\Microsoft\OpenXR /v "PreferD3D12" /d 0 /t REG_DWORD```

After running this command, open an OpenXR app and see if it fixes the problem.

**Comment by tksharpless** [comment]
That did not work.  App still acts as if it thinks the demo is running, but no picture.

**Comment by sahilagnihotri** [comment]
Hi! Is this issue resolved. I am also facing this issue. Fresh checkout and freash install of vs2019 with hololens2 and Windows mixed reality runtime version 107.2109.10010. Scene understanding and other samples work fine.

**Comment by mbucchia-msft** [comment]
No activity for a while. New releases of OS and OpenXR for WMR had several fixes which hopefully end up mitigating the various causes observed.
